// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://spefwkpbzkxplgbbquna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwZWZ3a3Biemt4cGxnYmJxdW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjg0OTgsImV4cCI6MjA3MTk0NDQ5OH0.F-YAv_rGZIyIbtnLRMl6RTtvB2w3J0n66WPHrNaKvJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);